### ISSUE TITLE
Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by jsbsdbd1025** [alibaba/vlayout#120]
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                   at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5690)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5445)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                   at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1607)
                                                                   at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:978)
                                                                   at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:117)
                                                                   at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:87)
                                                                   at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:280)
                                                                   at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
                                                                   at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
                                                                   at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
                                                                   at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                   at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2979)
                                                                   at com.jiang.common.base.irecyclerview.IRecyclerView.onMeasure(IRecyclerView.java:117)

**Comment by johnwatsondev** [comment]
```
VirtualLayoutManager.LayoutParams layoutParams = new VirtualLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.WRAP_CONTENT);
```
我们 `DelegateAdapter.Adapter` 子类中的 `onBindViewHolder(ActionItemViewHolder holder, int position)` 中不需要设置 `holder.itemView.setLayoutParams(new VirtualLayoutManager.LayoutParams(layoutParams));`，如果一定要设置的话必须给 layoutParams 传入新的 VirtualLayoutManager.LayoutParams ，然后再设置给 itemView。 你可以自己试试。

**Comment by longerian** [comment]
@jsbsdbd1025  我也看不出来原因，按照 @johnwatsondev 试试，看看前后有没有其他异常信息。
