### ISSUE TITLE
NullPointerException  ：LayoutState.mItemDirection

### ISSUE THREAD

**Issue by onionYJK** [alibaba/vlayout#147]
Process: com.cfinvo.standard, PID: 9536
                                                                   java.lang.NullPointerException: Attempt to read from field 'int com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.mItemDirection' on a null object reference
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.getItemDirection(VirtualLayoutManager.java:934)
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager.addChildView(VirtualLayoutManager.java:1062)
                                                                       at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:129)
                                                                       at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:87)
                                                                       at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:280)
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
                                                                       at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
                                                                       at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onFocusSearchFailed(ExposeLinearLayoutManagerEx.java:1344)
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager.onFocusSearchFailed(VirtualLayoutManager.java:67)
                                                                       at android.support.v7.widget.RecyclerView.focusSearch(RecyclerView.java:2332)
                                                                       at android.view.ViewGroup.focusSearch(ViewGroup.java:734)
                                                                       at android.view.ViewGroup.focusSearch(ViewGroup.java:734)
                                                                       at android.view.ViewGroup.focusSearch(ViewGroup.java:734)
                                                                       at android.view.ViewGroup.focusSearch(ViewGroup.java:734)
                                                                       at android.view.ViewGroup.focusSearch(ViewGroup.java:734)
                                                                       at android.view.View.focusSearch(View.java:7875)
                                                                       at android.widget.TextView.onCreateInputConnection(TextView.java:7194)
                                                                       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1519)
                                                                       at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1871)
                                                                       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3936)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6963)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by longerian** [comment]
找找复现场景，看看有没有异步操作，按正常流程，这个空指针如果可能发生，应该也是在更早的地方crash
