### ISSUE TITLE
IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder

### ISSUE THREAD

**Issue by lixi0912** [alibaba/vlayout#163]
Device: RedmiNote 3
SDK:  vlayout - 1.0.9
Andoird Version: 5.1.1

```java
FATAL EXCEPTION: main
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{26e7665 position=22 id=-1, oldPos=16, pLpos:16 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{155d9baf VFED.... ......ID 0,0-1080,1776 #7f080079 app:id/recycler}, adapter:com.alibaba.android.vlayout.DelegateAdapter@1c7f487d, layout:com.alibaba.android.vlayout.VirtualLayoutManager@37f62372, context:.activities.system.HomeActivity@1996797f
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5416)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5558)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5554)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1612)
        at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:978)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:110)
        at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:87)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:273)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1145)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:363)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3645)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3409)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3963)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15691)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.
```

**Comment by lixi0912** [comment]
mistake for used

**Comment by naturalStoryZhen** [comment]
Hi，My Product recently crashes on this issue，can you tell how to fix it？

**Comment by hzy00** [comment]
> mistake for use!

what‘s the problem?

**Comment by lixi0912** [comment]
@hzy00 

In my case, it was caused by the wrong position of the notifyXX method refresh

**Comment by hzy00** [comment]
okay, i also found the similar problem in my code: notifyItemInserted with wrong larger size.
