### ISSUE TITLE
GridLayoutHelper 设置spanCount导致的crash问题

### ISSUE THREAD

**Issue by dupengyun** [alibaba/vlayout#17]
#问题描述
 GridLayoutHelper 设置spanCount = 4 的是时候是可以正常运行的，但是设置spanCount =10 就会导 致下面的异常

#demo代码
```
  GridLayoutHelper helper = new GridLayoutHelper(10);
            helper.setAspectRatio(4f);
            //helper.setColWeights(new float[]{40, 20, 30, 30});
            // helper.setMargin(0, 10, 0, 10);
            helper.setGap(10);
            adapters.add(new SubAdapter(this, helper, 80) {
                @Override
                public void onBindViewHolder(MainViewHolder holder, int position) {
                    super.onBindViewHolder(holder, position);
                    LayoutParams lp = (LayoutParams) holder.itemView.getLayoutParams();
                    // lp.bottomMargin = 1;
                    // lp.rightMargin = 1;
                }
            });
```
#crash日志 
``` 
03-09 17:28:27.081 17103-17103/com.alibab.android.vlayout.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.alibab.android.vlayout.example, PID: 17103
                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
                                                                                        at android.support.v7.widget.RecyclerView.getChildViewHolder(RecyclerView.java:3399)
                                                                                        at android.support.v7.widget.RecyclerView.repositionShadowingViews(RecyclerView.java:3983)
                                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1496)
                                                                                        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2416)
                                                                                        at android.view.View.dispatchTouchEvent(View.java:10011)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
                                                                                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
                                                                                        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
                                                                                        at android.view.View.dispatchPointerEvent(View.java:10231)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4851)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4711)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4390)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4447)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
                                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6671)
                                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6645)
                                                                                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6606)
                                                                                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6798)
                                                                                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                                        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
                                                                                        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6745)
                                                                                        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6826)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:661)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
                                                                                        at android.os.Handler.handleCallback(Handler.java:761)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6524)
03-09 17:28:27.081 17103-17103/com.alibab.android.vlayout.example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

```

**Comment by longerian** [comment]
收到，待排查
