### ISSUE TITLE
多ViewHolder问题？

### ISSUE THREAD

**Issue by ansen666** [alibaba/vlayout#181]
您好，请问我有多个适配，每个适配器有不同ViewHolder，以下这些代码会报错
`at com.alibaba.android.vlayout.DelegateAdapter.onBindViewHolder(DelegateAdapter.java:138)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)`

我看你们官方的demo，只有一个静态的SubAdapter，如果我想不同的适配器不同的ViewHolder应该如何实现呢？

**Comment by longerian** [comment]
应该是复用相关的问题，参考FAQ：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md  先检查一下代码

**Comment by longerian** [comment]
#182  也可以参考一下

**Comment by ansen666** [comment]
好的 我先看看  谢谢大神 有问题我再来请教

**Comment by longerian** [comment]
你使用vlayout的上线产品吗，能不能到 #255 里登记一下

**Comment by ansen666** [comment]
现在还没上线。。等项目上线了来更新
