### ISSUE TITLE
使用过程中一个频繁出现错误

### ISSUE THREAD

**Issue by SkornZero** [alibaba/vlayout#19]
```java
03-10 00:09:02.842 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$ChildHelperWrapper.show(ExposeLinearLayoutManagerEx.java:1898)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.showView(ExposeLinearLayoutManagerEx.java:1425)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.showView(VirtualLayoutManager.java:1102)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.addChildView(VirtualLayoutManager.java:1067)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.addChildView(VirtualLayoutManager.java:1061)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:116)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:85)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:260)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1125)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343)
03-10 00:09:02.843 W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
03-10 00:09:02.844 W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
03-10 00:09:02.844 W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
03-10 00:09:02.844 W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
03-10 00:09:02.844 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.844 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.844 W/System.err:     at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
03-10 00:09:02.844 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.844 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.844 W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
03-10 00:09:02.844 W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
03-10 00:09:02.844 W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
03-10 00:09:02.844 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.844 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.844 W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-10 00:09:02.844 W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-10 00:09:02.844 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.844 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.844 W/System.err:     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
03-10 00:09:02.844 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.844 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.844 W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
03-10 00:09:02.844 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.844 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.844 W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-10 00:09:02.844 W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-10 00:09:02.845 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.845 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.845 W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-10 00:09:02.845 W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-10 00:09:02.845 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.845 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.845 W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
03-10 00:09:02.845 W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
03-10 00:09:02.845 W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
03-10 00:09:02.845 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.845 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.845 W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-10 00:09:02.845 W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-10 00:09:02.845 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.845 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.845 W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
03-10 00:09:02.845 W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
03-10 00:09:02.845 W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
03-10 00:09:02.845 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.845 W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-10 00:09:02.845 W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-10 00:09:02.845 W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-10 00:09:02.845 W/System.err:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
03-10 00:09:02.845 W/System.err:     at android.view.View.layout(View.java:17637)
03-10 00:09:02.864 W/art: Suspending all threads took: 5.079ms
03-10 00:09:02.867 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-10 00:09:02.867 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-10 00:09:02.867 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Log大概如上所示。在RecyclerView外部包裹了SwipeRefreshLayout的时候，在Swipe下拉过程中一直频繁出现这个错误，导致下拉的动画都出现明显卡顿

**Comment by longerian** [comment]
这是不兼容一个新版本的 recyclerview 产生的，已经修复，还未发布

**Comment by SkornZero** [comment]
在其他issue中看到解决方法，目前暂时将support版本降到23.1.1 能解决。希望尽快发布兼容最新support的版本。

**Comment by windwise** [comment]
啊哦，我也遇到这个问题。使用了1.0.5版本这个问题还在。

**Comment by longerian** [comment]
@windwise 你使用的recyclerView版本是什么 提供一下

**Comment by windwise** [comment]
@longerian 25.3.1
此前没注意到已经有人提了这个issue,这个问题跟#62一样

**Comment by longerian** [comment]
混淆配置说明也更新过了。
