### ISSUE TITLE
notifyDataSetChanged() bug

### ISSUE THREAD

**Issue by kgyntz** [alibaba/vlayout#199]
有个bug，我在text watcher中调用了DelegateAdapter.notifyDataSetChanged()
FATAL EXCEPTION: main
                                                                      Process: com.ngmm365.app.post, PID: 31919
                                                                      java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
                                                                          at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:459)
                                                                          at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
                                                                          at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1612)
                                                                          at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:996)
                                                                          at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:111)
                                                                          at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:87)
                                                                          at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:313)
                                                                          at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:592)
                                                                          at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1145)
                                                                          at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:363)
                                                                          at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:416)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3067)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.measure(RefreshContentWrapper.java:208)
                                                                          at com.scwang.smartrefresh.layout.SmartRefreshLayout.onMeasure(SmartRefreshLayout.java:552)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
                                                                          at android.view.View.measure(View.java:19917)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2436)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1482)
09-09 20:41:31.577 31919-31919/com.ngmm365.app.post E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1741)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                                          at android.os.Handler.handleCallback(Handler.java:761)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:156)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

什么原因，我要怎么改

**Comment by longerian** [comment]
可能用的版本比较老，和最新代码对不上，用1.1.0试试

**Comment by kgyntz** [comment]
不行的，无论换成多少版本的，还是报的java.lang.Object android.util.Pair.second
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
                                                                            at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:473)
                                                                            at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
                                                                            at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1626)
                                                                            at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1033)
                                                                            at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:116)
                                                                            at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:88)
                                                                            at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
                                                                            at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:629)
                                                                            at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1159)
                                                                            at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:363)
                                                                            at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:453)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
                                                                            at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3067)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.measure(RefreshContentWrapper.java:208)
                                                                            at com.scwang.smartrefresh.layout.SmartRefreshLayout.onMeasure(SmartRefreshLayout.java:552)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                            at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
                                                                            at android.view.View.measure(View.java:17562)
                                                                            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2052)
                                                                            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1210)
                                                                        	at android.view.ViewRootImpl.

**Comment by longerian** [comment]
你debug一下为什么，是index传错了，还是内部的mIndexAry  为空？
