### ISSUE TITLE
多个类型滑动闪退

### ISSUE THREAD

**Issue by QuincySx** [alibaba/vlayout#2]
03-05 12:44:18.381 27606-27606/com.example.a21vianet.vlayoutdemo D/AndroidRuntime: Shutting down VM
03-05 12:44:18.382 27606-27606/com.example.a21vianet.vlayoutdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.example.a21vianet.vlayoutdemo, PID: 27606
                                                                                   java.lang.IllegalArgumentException: Pixel distance must be non-negative
                                                                                       at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.addPosition(GapWorker.java:110)
                                                                                       at android.support.v7.widget.LinearLayoutManager.collectPrefetchPositionsForLayoutState(LinearLayoutManager.java:1202)
                                                                                       at android.support.v7.widget.LinearLayoutManager.collectAdjacentPrefetchPositions(LinearLayoutManager.java:1300)
                                                                                       at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.collectPrefetchPositionsFromView(GapWorker.java:94)
                                                                                       at android.support.v7.widget.GapWorker.buildTaskList(GapWorker.java:213)
                                                                                       at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:343)
                                                                                       at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by longerian** [comment]
与 #1  重复
