### ISSUE TITLE
使用stickyLayoutHelper时向上滑动程序Crash

### ISSUE THREAD

**Issue by hydrateam2016** [alibaba/vlayout#21]
`        
final StickyLayoutHelper stickyLayoutHelper = new StickyLayoutHelper();
        stickyLayoutHelper.setOffset(100);
        stickyLayoutHelper.setAspectRatio(4);
mAdapter.add(new DelegateAdapter.Adapter() {
            @Override
            public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                return new MyViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.top_item_doc,parent,false));
            }

            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder holder, final int position) {
                TextView tv= (TextView) ((MyViewHolder)holder).getView(R.id.tv_top_title);
                tv.setBackgroundColor(Color.BLUE);
                tv.setLayoutParams(new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,300));
                Log.e("/////////////", "onBindViewHolder: "+tv);
                ((MyViewHolder) holder).setText(tv,"这是标题"+position);
                tv.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Log.e("//////////", "onClick: "+position );
                    }
                });
            }

            @Override
            public int getItemCount() {
                return 1;
            }

            @Override
            public LayoutHelper onCreateLayoutHelper() {
                return stickyLayoutHelper;
            }
        });

        mAdapter.add(new DelegateAdapter.Adapter() {
            @Override
            public LayoutHelper onCreateLayoutHelper() {
                return new GridLayoutHelper(2);
            }

            @Override
            public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

                return new MyViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.top_item_doc,parent,false));
            }

            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder holder, final int position) {
                TextView tv= (TextView) ((MyViewHolder)holder).getView(R.id.tv_top_title);
                Log.e("/////////////", "onBindViewHolder: "+tv);
                ((MyViewHolder) holder).setText(tv,"这是标题"+position);
                tv.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Log.e("//////////", "onClick: "+position );
                    }
                });
            }

            @Override
            public int getItemCount() {
                return 100;
            }

            @Override
            public void onViewRecycled(RecyclerView.ViewHolder holder) {
                Log.e("/////", "onViewRecycled: ///////////" );
                super.onViewRecycled(holder);
            }

            @Override
            public int getItemViewType(int position) {
                if (position==0)return 3;
                return 2;
            }
        });`

向上滑动时候出现:
像素距离不能为非负数
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.doive.nameless.myvlayoudemo, PID: 13496
                                                                                 java.lang.IllegalArgumentException: Pixel distance must be non-negative
                                                                                     at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.addPosition(GapWorker.java:110)
                                                                                     at android.support.v7.widget.LinearLayoutManager.collectPrefetchPositionsForLayoutState(LinearLayoutManager.java:1194)
                                                                                     at android.support.v7.widget.LinearLayoutManager.collectAdjacentPrefetchPositions(LinearLayoutManager.java:1292)
                                                                                     at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.collectPrefetchPositionsFromView(GapWorker.java:94)
                                                                                     at android.support.v7.widget.GapWorker.buildTaskList(GapWorker.java:213)
                                                                                     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:343)
                                                                                     at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
                                                                                     at android.os.Handler.handleCallback(Handler.java:755)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by longerian** [comment]
使用新版本的 vlayout 1.0.2
