### ISSUE TITLE
用Vlayout的时候 相同type的复用是否会导致 图片也复用宽高 （Pair.second' on a null object ）

### ISSUE THREAD

**Issue by DavidNPF** [alibaba/vlayout#215]
每个helper的宽高都是不同的 
当我把DelegateAdapter(virtualLayoutManager,false)时  就会报空指针 
.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
                                                          at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:473)
                                                          at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
                                                          at com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF.onCreateViewHolderHF(RecyclerAdapterWithHF.java:86)
                                                          at com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF.onCreateViewHolder(RecyclerAdapterWithHF.java:94)
                                                          at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                          at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1626)
                                                          at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1033)
                                                          at com.alibaba.android.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:330)
                                                          at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:319)
                                                          at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:629)
                                                          at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1159)
                                                          at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:363)
                                                          at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:453)
                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at com.chanven.lib.cptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:266)
                                                          at com.chanven.lib.cptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:235)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:433)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                          at android.view.View.layout(View.java:15691)
                                                          at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                      	at android.view.View.layout(View.java

**Comment by grr1314** [comment]
我也遇到了这个问题

**Comment by longerian** [comment]
麻烦debug到那个地方看一下，可能内部计算有问题，我没有现场不好排查

**Comment by raulbest** [comment]
请问这个问题解决了么？

**Comment by raulbest** [comment]
> 每个helper的宽高都是不同的
> 当我把DelegateAdapter(virtualLayoutManager,false)时 就会报空指针
> .NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
> at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:473)
> at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
> at com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF.onCreateViewHolderHF(RecyclerAdapterWithHF.java:86)
> at com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF.onCreateViewHolder(RecyclerAdapterWithHF.java:94)
> at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
> at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
> at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
> at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1626)
> at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1033)
> at com.alibaba.android.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:330)
> at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:319)
> at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:629)
> at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1159)
> at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:363)
> at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:453)
> at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
> at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
> at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at com.chanven.lib.cptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:266)
> at com.chanven.lib.cptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:235)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:433)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java

你好，请问你这个问题解决了么？具体是怎么解决的？谢谢

**Comment by 1izheng** [comment]
> 每个helper的宽高都是不同的
> 当我把DelegateAdapter(virtualLayoutManager,false)时 就会报空指针
> .NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
> at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:473)
> at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
> at com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF.onCreateViewHolderHF(RecyclerAdapterWithHF.java:86)
> at com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF.onCreateViewHolder(RecyclerAdapterWithHF.java:94)
> at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
> at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
> at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
> at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1626)
> at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1033)
> at com.alibaba.android.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:330)
> at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:319)
> at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:629)
> at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1159)
> at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:363)
> at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:453)
> at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
> at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
> at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at com.chanven.lib.cptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:266)
> at com.chanven.lib.cptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:235)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:433)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15691)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java

请问这个问题解决了吗。同样遇到这个问题
