### ISSUE TITLE
DelegateAdapter remove 已经添加的adapter时,会出现holder类型转换问题

### ISSUE THREAD

**Issue by LzzzzzzC** [alibaba/vlayout#216]
java.lang.ClassCastException

**Comment by shenjianli** [comment]
确实有这样，问一下，可能尽快解决不？

**Comment by lixi0912** [comment]
```java
DelegateAdapter adapter;
// the itemViewTypes{0-N} of targetAdapter
adapter.removeAdapter(targetAdapter);
// clear RecycledViewPool after removeAdapter
```
1. 简单的处理是，在 remove 之后清除 RecycledViewPool 中的缓存 

```java
recyclerView.getRecycledViewPool().clear();
```
2. 根据ViewType，清除缓存。假设 targetAdapter 有 {0-N} 的 ViewType，adapter 在 DelegateAdapter 中的 index 是 0 (移除前)

```java
int DEFAULT_MAX_SCRAP = 5;
RecyclerView.RecycledViewPool pool = recyclerView.getRecycledViewPool();
for (int i = 0; i < N; i++) {
    int cantorViewType = DelegateAdapter.getCantor(i, adapterIndex);
    pool.setMaxRecycledViews(cantorViewType, 0);
    pool.setMaxRecycledViews(cantorViewType, DEFAULT_MAX_SCRAP);
}
```

**Comment by LinXiaoTao** [comment]
我也遇到这个问题。暂时通过设置不同的 `viewType` 来解决。

**Comment by LinXiaoTao** [comment]
@lixi0912 我通过调用 
``` java
.getRecycledViewPool().clear();
```
不起作用。。。

**Comment by longerian** [comment]
嗯  是有这个问题，暂时不太好解决，内部解决也是要做一次清理操作才行。

**Comment by lixi0912** [comment]
@LinXiaoTao  其实你说的通过 viewType 不完全能解决的，除非你在创建 `DelegateAdapter` 的时候设置 `hasConsistItemType`=true ，管理整个 DelegateAdapter 的 viewType 。

目前 addAdapterX、removeAdapterX 最终都会调用 `setAdapters` 而该方法第一行就是调用 `clear()` 重置 `mIndexGen`。这个时候，原来的 subAdapter 对应的 `index` 可能会发生改变 (addAdapter(int, Adapter)、addAdapters(int ,List<Adapter>)、removeAdapter(int))、removeFirstAdapter()、setAdapters(List<Adapter>)。

而 viewType 是根据 Adapter 的 `index` 和 item 的实际 `viewType` 根据 `Cantor` 配对算法生成的可逆值，这个时候 `index` 发生改变，同一个 Adapter，即使 viewType 没有变化也会导致原来的值和新生成的值不一致。

好了，说了一堆废话 :) ，如果 `getRecycledViewPool().clear()` 没有效果，可以跟下断点或者提供 log，才比较好发现问题

**Comment by LinXiaoTao** [comment]
@lixi0912 有点没太明白你说的。我还原下我的使用场景：
一开始先 `addAdapter` 添加两个 apdater，在执行完某个操作后，`removeAdapter` 之前添加的，再重新添加两个 adapter。
我也看过 `DelegateAdapter` 重新计算 sub adapter 的 viewType，是通过 sub adapter 的 index，和 sub adpter 返回的 viewType 综合重新计算的。
那么一开始删除了两个 sub adapter，又重新添加了两个 sub adapter，同时 sub adapter 返回的 viewType 不变的话，那么计算后的 viewType 应该是一致的。

**Comment by lixi0912** [comment]
@LinXiaoTao  
之前说的大致如下：
* 如果 `hasConsistItemType `=true, DelegateAdapter 会直接返回 subItemType ，不同 SubAdapter 之间相同的 subItemType 会复用 ViewHolder，所以当 `hasConsistItemType`= false 时，还是有可能会出现新计算的 CantorViewType 和缓存的 ViewHolder 出现冲突不对应
* 对 DeleteAdapter 的 SubAdapter 增加移除的操作都会重建 SubAdapter 的索引，会影响到 CantorViewType 的计算
* 只有 SubAdapter 的 index 和 itemViewType 不变， 计算合成的 CantorViewType 才不会变~ 这种情况下不会出现类型转换异常~  

你所讲的先移除再添加 ，需要详细的代码才能明白你具体的流程~

安全起见，每次对 DeleteAdapter 中的 SubAdapter 操作之前，确保对应的 subAdapter 数据是否需要进一步处理，然后再操作，最后在清下 RecyclerViewPool  的缓存~

**Comment by LinXiaoTao** [comment]
@lixi0912 
``` java
//init
mDelegateAdapter.setAdapters(Arrays.asList(mRecentSearchAdapter, mHotSearchAdapter));
//load data callback
public void onSearchEmpty(){
           mDelegateAdapter.setAdapters(Arrays
                   .asList(mCommoditySearchEmptyAdapter, mOtherSearchAdapter));
}
```
这种情况下，subAdapter 的 index 实际和第一次应该是相同的，viewType 也会计算一样。
这样的说法是否正确？

**Comment by lixi0912** [comment]
@LinXiaoTao  

可以这么说。假设 mCommoditySearchEmptyAdapter 和 mRecentSearchAdapter 的 ItemViewType 都是 {1,2,3} , 那么两个计算出来的 viewType 会一致，这个时候就会涉及到 这两个 Adapter 中 相同的 viewType 对应的 ViewHolder 是否可以转换。 不然的话 就得先清除  RecyclerViewPool, 还不行的话，就在之后再调用一次 notifyDataSetChanged 全局刷新一次~

```
//init
mDelegateAdapter.setAdapters(Arrays.asList(mRecentSearchAdapter, mHotSearchAdapter));
//load data callback
public void onSearchEmpty(){
        mDelegateAdapter.setAdapters(Arrays
            .asList(mCommoditySearchEmptyAdapter, mOtherSearchAdapter));
        mRecyclerView.getRecycledViewPool().clear();
        // mDelegateAdapter.notifyDataSetChanged(); 
}
```

**Comment by LinXiaoTao** [comment]
@lixi0912 
是的，这个四个 sub adapter 都是调用默认的 `super.getItemType(int)`，就会导致第二次 `setAdapters` 时，相同 `index` 的 sub adpter 出现缓存 viewholer 问题。
至于 `RecyclerViewPool.clear()` 没立即起作用，要看下源码才清楚了。
谢谢你的解答。

**Comment by lixi0912** [comment]
@LinXiaoTao  因为 setAdapters 中有 requestLayout 调用 所以，界面重绘比 `RecyclerViewPool.clear()` 更早，所以 才说操作 SubAdapter 的 增加移除时需要先确保是否需要设置数据，比如先移除数据，再移除 Adapter，在清缓存，再添加新的 Adapter，在通知界面变更。

当然，更好的优化需要大佬来做处理~

**Comment by LinXiaoTao** [comment]
@lixi0912 没看过源码，不知道这个修改 subAdapter 的数据对这个 viewType 的缓存问题有什么影响？能解答下吗？

**Comment by lixi0912** [comment]
@LinXiaoTao  将清除 View 的缓存放到设置之前~  似乎没有必要去管理那些数据~

```java
RecycledViewPool.clear();
delegateAdapter.setAdapters(newAdapters);
```

**Comment by longerian** [comment]
@lixi0912  总结一下，目前这个场景不管 hasConsistItemType 是否为 true，都需要subAdapter返回不同的 viewType来规避。

**Comment by appledong** [comment]
+1,麻烦问下楼上解决这个问题没？

**Comment by brucewuu520** [comment]
这个问题一直得不到解决啊，使用场景还是蛮多的

**Comment by longerian** [comment]
这个可以规避的，或者使用 tangram ，不用关心这些细节。

**Comment by e9ab98e991ab** [comment]
我的解决方式数据量不大 去掉了复用

**Comment by littlezan** [comment]
这个问题有没有什么解决方案啊，
我设置了
1. hasConsistItemType =true,
2. 每个subAdapter都是设置itemType
3. removeAdapter时候用recyclerPool.clear
4. 调用了adapter.notifyDataSetChange
还是会闪退啊
```
java.lang.ClassCastException: com.yupaopao.bixincrop.home.adapter.hometab.HomePageChooseFavoriteVoiceAdapter$ViewHolder cannot be cast to com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter$ViewHolder
        at com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter.onViewRecycled(HomePageActivityBannerAdapter.kt:26)
        at com.alibaba.android.vlayout.DelegateAdapter.onViewRecycled(DelegateAdapter.java:222)
        at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6485)
        at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:6256)
        at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6217)
        at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8945)
        at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8930)
        at com.alibaba.android.vlayout.VirtualLayoutManager.detachAndScrapAttachedViews(VirtualLayoutManager.java:1324)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:20831)
```

**Comment by e9ab98e991ab** [comment]
> 这个问题有没有什么解决方案啊，
> 我设置了
> 
> 1. hasConsistItemType =true,
> 2. 每个subAdapter都是设置itemType
> 3. removeAdapter时候用recyclerPool.clear
> 4. 调用了adapter.notifyDataSetChange
>    还是会闪退啊
> 
> ```
> java.lang.ClassCastException: com.yupaopao.bixincrop.home.adapter.hometab.HomePageChooseFavoriteVoiceAdapter$ViewHolder cannot be cast to com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter$ViewHolder
>         at com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter.onViewRecycled(HomePageActivityBannerAdapter.kt:26)
>         at com.alibaba.android.vlayout.DelegateAdapter.onViewRecycled(DelegateAdapter.java:222)
>         at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6485)
>         at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:6256)
>         at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6217)
>         at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8945)
>         at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8930)
>         at com.alibaba.android.vlayout.VirtualLayoutManager.detachAndScrapAttachedViews(VirtualLayoutManager.java:1324)
>         at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343)
>         at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
>         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
>         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
>         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
>         at android.view.View.layout(View.java:20831)
> ```

删除复用
RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool();
recyclerView.setRecycledViewPool(viewPool);
viewPool.setMaxRecycledViews(0, 10);
这三句话  就可以  简单的页面不要用  和好多有冲突 最好手写 封装一下最好

**Comment by littlezan** [comment]
> > 这个问题有没有什么解决方案啊，
> > 我设置了
> > 
> > 1. hasConsistItemType =true,
> > 2. 每个subAdapter都是设置itemType
> > 3. removeAdapter时候用recyclerPool.clear
> > 4. 调用了adapter.notifyDataSetChange
> >    还是会闪退啊
> > 
> > ```
> > java.lang.ClassCastException: com.yupaopao.bixincrop.home.adapter.hometab.HomePageChooseFavoriteVoiceAdapter$ViewHolder cannot be cast to com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter$ViewHolder
> >         at com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter.onViewRecycled(HomePageActivityBannerAdapter.kt:26)
> >         at com.alibaba.android.vlayout.DelegateAdapter.onViewRecycled(DelegateAdapter.java:222)
> >         at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6485)
> >         at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:6256)
> >         at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6217)
> >         at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8945)
> >         at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8930)
> >         at com.alibaba.android.vlayout.VirtualLayoutManager.detachAndScrapAttachedViews(VirtualLayoutManager.java:1324)
> >         at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343)
> >         at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
> >         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
> >         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
> >         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
> >         at android.view.View.layout(View.java:20831)
> > ```
> 
> 删除复用
> RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool();
> recyclerView.setRecycledViewPool(viewPool);
> viewPool.setMaxRecycledViews(0, 10);
> 这三句话 就可以 简单的页面不要用 和好多有冲突 最好手写 封装一下最好

兄弟，我没有设置这个

**Comment by e9ab98e991ab** [comment]
那你就检查你的代码吧，所有adapte需要在添加前初始化，后添加的就不行。我已经放弃使用vlayout了。 在2018年12月20日 20:34，littlezan 写道： 这个问题有没有什么解决方案啊， 我设置了 hasConsistItemType =true, 每个subAdapter都是设置itemType removeAdapter时候用recyclerPool.clear 调用了adapter.notifyDataSetChange 还是会闪退啊 java.lang.ClassCastException: com.yupaopao.bixincrop.home.adapter.hometab.HomePageChooseFavoriteVoiceAdapter$ViewHolder cannot be cast to com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter$ViewHolder

        at com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter.onViewRecycled(HomePageActivityBannerAdapter.kt:26)

        at com.alibaba.android.vlayout.DelegateAdapter.onViewRecycled(DelegateAdapter.java:222)

        at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6485)

        at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:6256)

        at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6217)

        at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8945)

        at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8930)

        at com.alibaba.android.vlayout.VirtualLayoutManager.detachAndScrapAttachedViews(VirtualLayoutManager.java:1324)

        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343)

        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)

        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)

        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)

        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)

        at android.view.View.layout(View.java:20831)

 删除复用 RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool(); recyclerView.setRecycledViewPool(viewPool); viewPool.setMaxRecycledViews(0, 10); 这三句话 就可以 简单的页面不要用 和好多有冲突 最好手写 封装一下最好 兄弟，我没有设置这个 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by LinXiaoTao** [comment]
想放弃 +1，这感觉是个 KPI 项目

**Comment by littlezan** [comment]
> 想放弃 +1，这感觉是个 KPI 项目

真后悔用了这个库，国外的项目，人家都很勤快回答问题

**Comment by littlezan** [comment]
> 那你就检查你的代码吧，所有adapte需要在添加前初始化，后添加的就不行。我已经放弃使用vlayout了。 在2018年12月20日 20:34，littlezan 写道： 这个问题有没有什么解决方案啊， 我设置了 hasConsistItemType =true, 每个subAdapter都是设置itemType removeAdapter时候用recyclerPool.clear 调用了adapter.notifyDataSetChange 还是会闪退啊 java.lang.ClassCastException: com.yupaopao.bixincrop.home.adapter.hometab.HomePageChooseFavoriteVoiceAdapter$ViewHolder cannot be cast to com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter$ViewHolder at com.yupaopao.bixincrop.home.adapter.hometab.HomePageActivityBannerAdapter.onViewRecycled(HomePageActivityBannerAdapter.kt:26) at com.alibaba.android.vlayout.DelegateAdapter.onViewRecycled(DelegateAdapter.java:222) at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6485) at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:6256) at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6217) at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8945) at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8930) at com.alibaba.android.vlayout.VirtualLayoutManager.detachAndScrapAttachedViews(VirtualLayoutManager.java:1324) at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343) at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463) at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924) at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641) at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194) at android.view.View.layout(View.java:20831) 删除复用 RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool(); recyclerView.setRecycledViewPool(viewPool); viewPool.setMaxRecycledViews(0, 10); 这三句话 就可以 简单的页面不要用 和好多有冲突 最好手写 封装一下最好 兄弟，我没有设置这个 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

肯定是先new出来的

**Comment by littlezan** [comment]
总结一把，removeAdapter这个最好还是别用了吧，我最后是把这个subAdapter隐藏掉，才解决了崩溃的问题
1. 
```
delegateAdapterInside.notifyItemChanged(deleteHeadAdapter.currentPosition)
```

```
viewHolder.itemView.visibility = View.GONE
viewHolder.itemView.layoutParams = VirtualLayoutManager.LayoutParams(0, 0)
```

**Comment by JunnanLee** [comment]
这个库好垃圾，我首页做了缓存，上来会先加载上次的数据，然后新的数据拉取回来之后就会报ClassCastException

**Comment by safe-ending** [comment]
recyclerView.addAdapter(1);
recyclerView.addAdapter(2);
recyclerView.addAdapter(3);
 ...
mDelegateAdapter.clear();
recyclerView.setAdapter(mDelegateAdapter);
...
recyclerView.addAdapter(1);
recyclerView.addAdapter(3);
这样就ok了不会出现复用的了
mDelegateAdapter.clear();
recyclerView.setAdapter(mDelegateAdapter);

**Comment by githubxiaoou** [comment]
mAdapter.clear();
                mAdapter.addAdapter(mLessonTagAdapter);
                mAdapter.addAdapter(mLessonAdapter);
                if (!test) {
                    mAdapter.addAdapter(mLectureTagAdapter);
                }
                mAdapter.addAdapter(mLectureAdapter);
                mAdapter.addAdapter(mHallTagAdapter);
                mAdapter.addAdapter(mHallAdapter);
                if (test) {
                    mAdapter.addAdapter(mEmptySingleLayoutAdapter);
                }
                mBinding.rv.setAdapter(mAdapter);

全部clear后重新按顺序添加，然后重新setAdapter，这样可行
