### ISSUE TITLE
调用notifyDataSetChanged出现IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ania93** [alibaba/vlayout#229]
调用notifyDataSetChanged出现数组越界，debug发现是RangeLayoutHelperFinder中mLayoutHelpers是空的，想问下是咋回事？
调用：
 if (mMatronRecommendOrderAdapter != null) {
                mMatronRecommendOrderAdapter.setData(mMatronRecommendOrderList);
                mMatronRecommendOrderAdapter.notifyDataSetChanged();
 }
异常log：
java.lang.IndexOutOfBoundsException at java.util.LinkedList.get(LinkedList.java:519)
at com.alibaba.android.vlayout.DelegateAdapter$AdapterDataObserver.updateLayoutHelper(DelegateAdapter.java:511)
at com.alibaba.android.vlayout.DelegateAdapter$AdapterDataObserver.onChanged(DelegateAdapter.java:534)
at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11359)
at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6636)

**Comment by ania93** [comment]
先初始化view再更新数据，已经解决~

**Comment by HowieTianDev** [comment]
我也遇到了这个问题，第一次设置数据是正常的，第二次刷新数据再notify的时候就找不到helper了，能和我说下，你是怎么解决的吗，非常感谢。
