### ISSUE TITLE
当使用FixLayoutHelper(TOP_RIGHT, 0, 0)时，布局发生错误，并有几率crash

### ISSUE THREAD

**Issue by bawuju** [alibaba/vlayout#245]
- 使用`FixLayoutHelper(TOP_RIGHT, 0, 0)`会出现布局错误，滑动的时候还会crash。用`FixLayoutHelper(0, 0)`时正常。
- crash:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
    at android.support.v7.widget.RecyclerView.getChildViewHolder(RecyclerView.java:3399)
    at android.support.v7.widget.RecyclerView.repositionShadowingViews(RecyclerView.java:3983)
    at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1496)
    at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2416)
    at android.view.View.dispatchTouchEvent(View.java:9306)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2820)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
    at android.view.View.dispatchPointerEvent(View.java:9526)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4267)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4133)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5959)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5933)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5894)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6062)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6033)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6085)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
    at android.view.Choreographer.doFr
```
- 初始化代码:
```java
RecyclerView recyclerView = findViewById(R.id.recycler_view);
VirtualLayoutManager virtualLayoutManager = new VirtualLayoutManager(this);
DelegateAdapter delegateAdapter = new DelegateAdapter(virtualLayoutManager);
List<DelegateAdapter.Adapter> adapterList = new ArrayList<>();
adapterList.add(new SubAdapter(new LinearLayoutHelper(20), 20));
adapterList.add(new SubAdapter(new StickyLayoutHelper(true), 1));
adapterList.add(new SubAdapter(new LinearLayoutHelper(20), 20));
adapterList.add(new SubAdapter(new GridLayoutHelper(4), 80));
// adapterList.add(new SubAdapter(new FixLayoutHelper(0, 0), 1));
adapterList.add(new SubAdapter(new FixLayoutHelper(TOP_RIGHT, 0, 0), 1));
delegateAdapter.addAdapters(adapterList);
recyclerView.setLayoutManager(virtualLayoutManager);
recyclerView.setAdapter(delegateAdapter);
```
- SubAdapter:
```java
private static class SubAdapter extends DelegateAdapter.Adapter<SubViewHolder> {

    private LayoutHelper mLayoutHelper;
    private int mItemCount;

    private SubAdapter(LayoutHelper layoutHelper, int itemCount) {
        mLayoutHelper = layoutHelper;
        mItemCount = itemCount;
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        return mLayoutHelper;
    }

    @Override
    public SubViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        return new SubViewHolder(inflater.inflate(R.layout.item_layout, parent, false));
    }

    @Override
    public void onBindViewHolder(SubViewHolder holder, int position) {
        // do nothing
    }

    @Override
    protected void onBindViewHolderWithOffset(SubViewHolder holder, int position, int offsetTotal) {
        super.onBindViewHolderWithOffset(holder, position, offsetTotal);
        holder.setText(String.valueOf(offsetTotal));
        holder.itemView.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
    }

    @Override
    public int getItemCount() {
        return mItemCount;
    }

}
```

**Comment by longerian** [comment]
recyclerView是什么版本

**Comment by bawuju** [comment]
@longerian recyclerview是23.1.1   appcompat-v7是26.1.0    vlayout是1.2.2

**Comment by bawuju** [comment]
@longerian `SubViewHolder`的代码我不贴了，没什么东西，layout是
```
<ConstraintLayout>
    <TextView/>
<ConstraintLayout/>
```

**Comment by longerian** [comment]
代码这么写是没问题，fixlayoutHelper里有几个item？   只能支持一个

**Comment by bawuju** [comment]
@longerian 就一个FixLayoutHelper，直接new了，没有设置itemCount。itemCount是从`SubAdapter.getItemCount()`返回的，值是1（构造函数传入）

**Comment by bawuju** [comment]
@longerian 多滑动几次，GridLayout中间会有重合或者断开，布局有错位，也可能会直接crash

**Comment by longerian** [comment]
看看每个subadapter返回的个数，与layouterhelper的设置 是不是都匹配

**Comment by bawuju** [comment]
@longerian 我没有给LayoutHelper设置itemCount, 只设置了adapter的。我看了源码，当adapter和layoutHelper的itemCount不相等的时候，以adapter的为准，所以应该都是匹配的吧。

**Comment by longerian** [comment]
这个 需要再排查下，可能是滑动过程中itemView被某个场景下删除了。
