### ISSUE TITLE
SmartRefreshLayout + vlayout 刷新时碰到的问题

### ISSUE THREAD

**Issue by aljian** [alibaba/vlayout#266]
` java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
                                                                    at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:473)
                                                                    at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
                                                                    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)

如上所示 ,刷新时的错误 是我哪写错了还是怎么的 请大佬们 指点 ,万分感谢

**Comment by longerian** [comment]
断电一下crash这个方法传入的index是多少，可能索引取错了

aljian <notifications@github.com>于2017年12月14日 周四10:21写道：

**Comment by aljian** [comment]
int index = viewType - t; 正常启动时 viewType= 0  t = 0 然后后面的跟着排序
刷新的时候  viewType  = -1 然后错误了

**Comment by aljian** [comment]
@longerian 大佬  我一个一个 调试了下 发现 是LinearLayoutHelper这个的问题 `productList = new ArrayList<>();
        if (LINEAR_LAYOUT) {
            LinearLayoutHelper linearLayoutHelper = new LinearLayoutHelper();
            proListAdapter = new VProListAdapter(getActivity(), linearLayoutHelper, productList);
            adapters.add(proListAdapter);
        }` 一旦刷新这个里的数据 viewType 就会 == -1 
别的GridLayoutHelper SingleLayoutHelper 都没问题

**Comment by longerian** [comment]
```
Pair<AdapterDataObserver, Adapter> p = findAdapterByPosition(position);
        if (p == null) {
            return RecyclerView.INVALID_TYPE;
        }

```

根据这个逻辑，你的position错了，所以看看position为什么错了。

**Comment by longerian** [comment]
我们也用这个库测过了，是可以run起来的

**Comment by aljian** [comment]
大佬,我的问题最后解决了 
第一个,我原来的 采用的clear方法
`public void refresh(){
productList.clear();
getData();
proListAdapter.notifyDataSetChanged();
}`
第二个是之后的 `public void refresh(){
productList = new ArrayList<>();
getData();
proListAdapter.notifyDataSetChanged();
}`
我是用第二种方法解决的     
new的没问题 但是clear就GG了 我最后也没找到是什么原因.................

**Comment by longerian** [comment]
直接clear是不太好，因为layouthelper内部信息并没有同步更新到位，比较容易出问题。

**Comment by aljian** [comment]
额,谢谢大佬!辛苦大佬帮我解决了

**Comment by raulbest** [comment]
> 额,谢谢大佬!辛苦大佬帮我解

你好，请问这个报错问题你具体是怎么解决的，谢谢！
