### ISSUE TITLE
NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType'

### ISSUE THREAD

**Issue by a512509050** [alibaba/vlayout#285]
异常日志：
```
java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
                                                                at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6520)
                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1629)
                                                                at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1043)
                                                                at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:116)
                                                                at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:88)
                                                                at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
                                                                at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:639)
                                                                at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1162)
                                                                at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
                                                                at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:206)
                                                                at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:690)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                at com.android.internal.policy.DecorView.onLayout(DecorView.java:752)
                                                                at android.view.View.layout(View.java:18071)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2748)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2413)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1496)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7131)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:912)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:714)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:648)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:898)
                                                                at android.os.Handler.handleCallback(Handler.java:836)
                                                                at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                at android.os.Looper.loop(Looper.java:203)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6475)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```
每次刷新数据就出现这个bug
```
//vLayout初始化
        VirtualLayoutManager layoutManager = new VirtualLayoutManager(getContext());
        layoutManager.setRecycleOffset(300);
        mRecyclerView.setLayoutManager(layoutManager);

        final RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool();
        mRecyclerView.setRecycledViewPool(viewPool);
        viewPool.setMaxRecycledViews(0, 10);

        final DelegateAdapter delegateAdapter = new DelegateAdapter(layoutManager, true);

        final LinkedList<DelegateAdapter.Adapter> adapters = new LinkedList<>();

        mBannerAdapter = initBannerAdapter();
        adapters.add(mBannerAdapter);

       mNoticeAdapter = initNoticeAdapter();
        adapters.add(mNoticeAdapter);
       //只添加Banner和NoticeAdapter不会崩溃，加上下面的就会崩溃_
       mShopAdapter = initRecommendShopAdapter();
        adapters.add(mShopAdapter);
       
       delegateAdapter.addAdapters(adapters);

       mRecyclerView.setAdapter(delegateAdapter);
```
```
/**
     * 初始化Banner adapter
     *
     * @return {{@link SubAdapter}}
     */
    private SubAdapter initBannerAdapter() {

        return new SubAdapter(getContext(), new LinearLayoutHelper()) {
            @Override
            public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                if (viewType == Constants.TYPE_HOME_BANNER) {
                    return new ViewHolder(LayoutInflater.from(getContext()).inflate(R.layout.item_banner, parent, false));
                } else {
                    return super.onCreateViewHolder(parent, viewType);
                }
            }

            @Override
            public void onBindViewHolder(ViewHolder holder, int position) {
                /*super.onBindViewHolder(holder, position);*/
                if (holder.itemView instanceof Banner) {
                    final Banner banner = (Banner) holder.itemView;
                    banner.startAutoPlay();
                    ...
                }
            }

            @Override
            public void onViewRecycled(ViewHolder holder) {
                // item被回收后置空adapter
                if (holder.itemView instanceof Banner) {
                    Banner banner = (Banner) holder.itemView;
                    banner.stopAutoPlay();
                }
            }

            @Override
            public int getItemViewType(int position) {
                return Constants.TYPE_HOME_BANNER;
            }
        };
    }

   /**
     * 初始化轮播公告adapter
     *
     * @return {@link SubAdapter}
     */
    private SubAdapter initNoticeAdapter() {
        return new SubAdapter(getContext(), new LinearLayoutHelper()) {
            @Override
            public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                if (viewType == Constants.TYPE_HOME_NOTICE) {
                    return new ViewHolder(LayoutInflater.from(getContext()).inflate(R.layout.item_notice, parent, false));
                } else {
                    return super.onCreateViewHolder(parent, viewType);
                }
            }

            @Override
            public void onBindViewHolder(ViewHolder holder, int position) {
                MarqueeView marqueeView = holder.itemView.findViewById(R.id.mv_notice);
                if (marqueeView != null) {
                    marqueeView.startFlipping();
                    ....
                }
            }

            @Override
            public void onViewRecycled(ViewHolder holder) {
                // item被回收后置空adapter
                MarqueeView marqueeView = holder.itemView.findViewById(R.id.mv_notice);
                if (marqueeView != null) {
                    marqueeView.stopFlipping();
                }
            }

            @Override
            public int getItemViewType(int position) {
                return Constants.TYPE_HOME_NOTICE;
            }
        };
    }

    private SubAdapter initRecommendShopAdapter() {
        return new SubAdapter(getContext(), new LinearLayoutHelper()) {
            @Override
            public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                if (viewType == Constants.TYPE_HOME_RECOMMENDED_SHOP_ITEM) {
                    return new ViewHolder(LayoutInflater.from(getContext()).inflate(R.layout.item_shop_detail, parent, false));
                } else {
                    return super.onCreateViewHolder(parent, viewType);
                }
            }

            @Override
            public void onBindViewHolder(ViewHolder holder, int position) {
               ...
            }

            @Override
            public int getItemCount() {
                return mRecommendList.size();
            }

            @Override
            public int getItemViewType(int position) {
                return Constants.TYPE_HOME_RECOMMENDED_SHOP_ITEM;
            }
        };
    }
```
网络请求
```
private List<BannerBean>   mBannerList    = new ArrayList<>();
private List<NoticeBean>   mNoticeList    = new ArrayList<>();
private List<ShopItemBean> mRecommendList = new ArrayList<>();
private void initRequest() {
        mBannerList.clear();
        mNoticeList.clear();
        mRecommendList.clear();
        mPresenter.getBanner();
        mPresenter.getNotice();
        mPresenter.getRecommendShops();
    }

@Override
    public void setBanner(List<BannerBean> beanList) {
        mBannerList.addAll(beanList);
        mBannerAdapter.notifyDataSetChanged();
    }

    @Override
    public void setNotice(List<NoticeBean> beanList) {
        mNoticeList.addAll(beanList);
        mNoticeAdapter.notifyDataSetChanged();
    }

    @Override
    public void setRecommendList(List<ShopItemBean> list) {
        mRecommendList.addAll(list);
        mShopAdapter.notifyDataSetChanged();
    }
```

**Comment by longerian** [comment]
recommendList 数据有多少个

**Comment by a512509050** [comment]
有4条

**Comment by longerian** [comment]
你的recyclerView 版本是多少，  有没有开启prefetch功能

**Comment by a512509050** [comment]
版本是26.1.0， prefetch这个功能并没有去设置

**Comment by longerian** [comment]
new DelegateAdapter(layoutManager, true); 这个改成   new DelegateAdapter(layoutManager, false); 吧，试试看， FAQ 先看看，
网上也查查资料，应该是和下面这些问题一样的原因。
http://blog.csdn.net/xinpengfei521/article/details/53270688
http://blog.csdn.net/allan_bst/article/details/68958541

**Comment by weimingjue** [comment]
代码肯定走super的onCreateViewHolder了,崩溃的rv源码如下
public final VH createViewHolder(ViewGroup parent, int viewType) {
TraceCompat.beginSection(TRACE_CREATE_VIEW_TAG);
final VH holder = onCreateViewHolder(parent, viewType);
holder.mItemViewType = viewType;//此处崩溃,很明显onCreateViewHolder返回null了
TraceCompat.endSection();
return holder;
}


根据你的代码目前只看到了一种可能:看你在主线程clear了所有的list但并没有立即notifyadapter(等到网络请求回来再notify已经晚了).list的size发生改变就必须立即notifyadapter,很多人都没有意识到这个问题
