### ISSUE TITLE
多种Adapter多种数据 转换异常

### ISSUE THREAD

**Issue by QuincySx** [alibaba/vlayout#3]
java.lang.ClassCastException: com.example.a21vianet.vlayoutdemo.homeitem.sort.SortBannerProvider$ViewHolder cannot be cast to com.example.a21vianet.vlayoutdemo.homeitem.bar.BarBannerProvider$ViewHolder
                                                                                       at com.example.a21vianet.vlayoutdemo.homeitem.bar.BarBannerProvider.onBindViewHolder(BarBannerProvider.java:37)
                                                                                       at com.alibaba.android.vlayout.DelegateAdapter.onBindViewHolder(DelegateAdapter.java:135)
                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6310)
                                                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6343)
                                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5289)
                                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5552)
                                                                                       at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:270)
                                                                                       at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
                                                                                       at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
                                                                                       at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
                                                                                       at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by longerian** [comment]
你写了三个自定义的```DelegateAdapter.Adapter```，每个都通过泛型绑定了自定义的```RecyclerView.ViewHolder```子类，分别是：```BarBannerProvider.ViewHolder```，```AdBannerProvider.ViewHolder```，```SortBannerProvider.ViewHolder```。

这样的话，每个```DelegateAdapter.Adapter```的```public void onBindViewHolder(ViewHolder holder, int position)```方法参数都是自定义的类型，系统调用的时候会有一次强转，转换出错。

正确的使用方式是：
1. 自定义 Adapter 绑定统一的```RecyclerView.ViewHolder```泛型，在 adapter 的```public void onBindViewHolder(ViewHolder holder, int position)```自己做类型强制；

或者

2. 不同的自定义 Adapter 采用统一的自定义的```RecyclerView.ViewHolder```子类，在分别处理业务逻辑；

**Comment by QuincySx** [comment]
ok，感谢

**Comment by QuincySx** [comment]
@longerian 经测试这个转换异常只需设置public int getItemViewType(int position)即可。无需自己做类型强转或同意ViewHolder

**Comment by longerian** [comment]
同意

**Comment by siyehua** [comment]
发现此问题在ry 23.3.1不存在,但是滑动非常卡,
如果使用25.2.0,则必须对每一个Adapter的getItemViewType(int position)重写,滑动也不卡
[使用例子](https://github.com/siyehua/VLayoutTest/tree/master)

**Comment by yanxinmiao** [comment]
@QuincySx 确实如此，adapter只要实现getItemViewType() ， 就没有这个问题了，而且recycleview滑动也不卡了

**Comment by longerian** [comment]
@siyehua @yanxinmiao @QuincySx 
有使用vlayout的上线产品吗，能不能到 #255 里登记一下
