### ISSUE TITLE
你好，公司在线上项目中使用vlayout时偶尔会报IndexOutOfBoundsException异常，导致应用崩溃

### ISSUE THREAD

**Issue by tik5213** [alibaba/vlayout#308]
你好，公司在线上项目中使用SwipeRefreshLayout + vlayout时偶尔会报IndexOutOfBoundsException异常，导致应用崩溃。下面是异常信息。
------------------------------------------------

```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1ac1ef34 position=22 id=-1, oldPos=13, pLpos:13 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{30408610 VFED.V.. ......I. 0,0-1080,1530 #7f11014d app:id/rv_list}, adapter:com.alibaba.android.vlayout.b@dce7854, layout:com.alibaba.android.vlayout.VirtualLayoutManager@2e8b03fd, context:cn.dxy.android.aspirin.ui.activity.MainActivity@eda83bb
	at android.support.v7.widget.RecyclerView$m.a(RecyclerView.java:5447)
	at android.support.v7.widget.RecyclerView$m.a(RecyclerView.java:5629)
	at android.support.v7.widget.RecyclerView$m.a(RecyclerView.java:5589)
	at android.support.v7.widget.RecyclerView$m.c(RecyclerView.java:5585)
	at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$c.a(ExposeLinearLayoutManagerEx.java:1629)
	at com.alibaba.android.vlayout.VirtualLayoutManager$e.a(VirtualLayoutManager.java:1043)
	at com.alibaba.android.vlayout.a.a.a(BaseLayoutHelper.java:116)
	at com.alibaba.android.vlayout.a.g.b(LinearLayoutHelper.java:88)
	at com.alibaba.android.vlayout.a.a.a(BaseLayoutHelper.java:318)
	at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:639)
	at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1162)
	at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
	at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
	at android.support.v7.widget.RecyclerView.N(RecyclerView.java:3670)
	at android.support.v7.widget.RecyclerView.q(RecyclerView.java:3434)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.support.design.widget.h.b(HeaderScrollingViewBehavior.java:132)
	at android.support.design.widget.p.a(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.a(AppBarLayout.java:1361)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at cn.dxy.library.SwipeBackLayout.onLayout(SwipeBackLayout.java:208)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2544)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2234)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1331)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6792)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:804)
	at android.view.Choreographer.doCallbacks(Choreographer.java:607)
	at android.view.Choreographer.doFrame(Choreographer.java:576)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:790)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5929)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

**Comment by longerian** [comment]
这个可能是你数据异步更新了没有通知到界面，你网上搜搜这个crash，很多信息的，找点思路，检查下代码。
