### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference

### ISSUE THREAD

**Issue by JakeWoki** [alibaba/vlayout#33]
``` Java
Process: com.alibab.android.vlayout.example, PID: 16415
                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
                                                                                        at android.support.v7.widget.RecyclerView.getChildViewHolder(RecyclerView.java:4222)
                                                                                        at android.support.v7.widget.RecyclerView.repositionShadowingViews(RecyclerView.java:4911)
                                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1699)
                                                                                        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2883)
                                                                                        at android.view.View.dispatchTouchEvent(View.java:8503)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2402)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2387)
                                                                                        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1734)
                                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2833)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2348)
                                                                                        at android.view.View.dispatchPointerEvent(View.java:8698)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4415)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4281)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3779)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3832)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3798)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3915)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3806)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3972)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3779)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3832)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3798)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3806)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3779)
                                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6125)
                                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6080)
                                                                                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6051)
                                                                                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6226)
                                                                                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6186)
                                                                                        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6253)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:612)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:579)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                                                    	at java.lang.reflect.Method.invoke(Nati
```
不知道怎么操作出来的，重现不了  25.3.0

**Comment by longerian** [comment]
有提过类似的bug，还没解决

**Comment by JakeWoki** [comment]
https://github.com/alibaba/vlayout/issues/17
