### ISSUE TITLE
java.lang.ClassCastException: com.alibaba.android.vlayout.VirtualLayoutManager$LayoutViewHolder

### ISSUE THREAD

**Issue by blackberry2016** [alibaba/vlayout#331]
完全自定义一个自己的DelegateAdapter。也自定义了ViewHolder，在增添divider的时候报异常
```
    java.lang.ClassCastException: com.alibaba.android.vlayout.VirtualLayoutManager$LayoutViewHolder cannot be cast to com.pacific.adapter.ViewHolder
        at com.pacific.adapter.VLayoutDelegateAdapter.onViewDetachedFromWindow(VLayoutDelegateAdapter.java:13)
        at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6819)
        at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:727)
        at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:7913)
```
代码信息

```
LinearLayoutHelper linearLayoutHelper = new LinearLayoutHelper();
        linearLayoutHelper.setBgColor(ContextCompat.getColor(this, R.color.mark_input));
        linearLayoutHelper.setDividerHeight(getResources().getDimensionPixelSize(R.dimen.mark_subject_divider));
        VLayoutRecyclerAdapter adapterIntroduction = new VLayoutRecyclerAdapter(linearLayoutHelper);
```

**Comment by longerian** [comment]
复用的时候类型错了 ， 可以看faq 再了解下 
 https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#%E7%BB%84%E4%BB%B6%E5%A4%8D%E7%94%A8%E7%9A%84%E9%97%AE%E9%A2%98
