### ISSUE TITLE
DelegateAdapter.onViewRecycled 必现Crash

### ISSUE THREAD

**Issue by mortoncui** [alibaba/vlayout#336]
当DelegateAdapter.Adapter覆写了onViewRecycled方法后,会出现java.lang.ClassCastException
CrashException: java.lang.ClassCastException: TitleAdapter$Holder cannot be cast to NormalItemAdapter$ItemViewHolder
                                                                              at NormalItemAdapter.onViewRecycled(NormalItemAdapter.java:50)
                                                                              at com.alibaba.android.vlayout.DelegateAdapter.onViewRecycled(DelegateAdapter.java:227)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:6056)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:5827)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5792)
                                                                              at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8462)
                                                                              at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8447)
                                                                              at com.alibaba.android.vlayout.VirtualLayoutManager.detachAndScrapAttachedViews(VirtualLayoutManager.java:1348)
                                                                              at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:343)
                                                                              at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:475)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                              at android.view.View.layout(View.java:19781)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6144)

**Comment by mortoncui** [comment]
补充下,不同的subAdapter均返回不同的viewType

**Comment by mortoncui** [comment]
是这样的,首次填充内容是正常的
如 
mDelegateAdapter.addAdapters(adapters)

但是在某些情况下,如要动态调整某个adapters中包含数据的数量
如adapters.get(0)的getItemCount数量变多了,
导致adapters.get(1)创建出来的一些View由不可见变为可见,从而被recycled,出现crash情形

**Comment by longerian** [comment]
那应该还是类型复用出错了 你看看 recyclerview 内部拿到的 type 有没有问题，符不符合预期

**Comment by mortoncui** [comment]
布局/展示的时候是没有问题的.复用类型是正确的,只是回收的时候会出现.当前面的adapter中的View数量增加而导致页面下面的View被回收时必现该crash
