### ISSUE TITLE
 java.lang.NullPointerException: Attempt to read from field 'int android.support.v7.widget.ViewInfoStore$InfoRecord.flags' on a null object reference

### ISSUE THREAD

**Issue by MarsHou** [alibaba/vlayout#338]
There is no exception in project development, However, the release apk reported exception on bugly.
```
04-16 08:01:54.942 8489 8489 E AndroidRuntime: FATAL EXCEPTION: main
04-16 08:01:54.942 8489 8489 E AndroidRuntime: Process: com.demo, PID: 8489
04-16 08:01:54.942 8489 8489 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.support.v7.widget.ViewInfoStore$InfoRecord.flags' on a null object reference
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:222)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3789)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3447)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.View.layout(View.java:19612)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6055)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2509)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1411)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6785)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:780)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:715)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:789)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:98)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6665)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-16 08:01:54.942 8489 8489 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by growupzyg** [comment]
@MarsHou 这个问题查到原因了么 我也遇到同样的问题了

**Comment by YanYanLun** [comment]
这个问题查到原因了么 我也遇到同样的问题了

**Comment by MarsHou** [comment]
@growupzyg @YanYanLun 没有呢 我这并不是必现的，自己的测试机上也没出现过，只在bugly上有看到个别用户碰到了，不好排查原因
