### ISSUE TITLE
页面刷新调用DelegateAdapter.clear()后用addAdapter与之前不同的adapter，页面会报ClassCastException

### ISSUE THREAD

**Issue by lancelfj** [alibaba/vlayout#340]
UncaughtException detected: java.lang.ClassCastException: tiangong.com.pu.module.home.adapter.HomeAdapterType3$MyViewHolder cannot be cast to tiangong.com.pu.module.home.adapter.HomeAdapterEventType$MyViewHolder
                                                                 at tiangong.com.pu.module.home.adapter.HomeAdapterEventType.onBindViewHolder(HomeAdapterEventType.java:32)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                 at com.alibaba.android.vlayout.DelegateAdapter.onBindViewHolder(DelegateAdapter.java:150)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                 at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1629)
                                                                 at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1065)
                                                                 at com.alibaba.android.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:330)
                                                                 at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
                                                                 at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:657)
                                                                 at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1162)
                                                                 at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
                                                                 at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:475)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)

貌似clear后，原来的viewhold没有被clear

**Comment by raulbest** [comment]
我也遇到了这个情况，请问这个你那边解决了么？

**Comment by e9ab98e991ab** [comment]
这个问题比较坑 你们解决没？
