### ISSUE TITLE
页面中偶尔会有这种报错

### ISSUE THREAD

**Issue by raulbest** [alibaba/vlayout#353]
java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
                                                               at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6494)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                               at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1629)
                                                               at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1065)
                                                               at com.alibaba.android.vlayout.layout.SingleLayoutHelper.layoutViews(SingleLayoutHelper.java:78)
                                                               at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
                                                               at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:657)
                                                               at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1162)
                                                               at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
                                                               at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:475)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1096)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                               at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2757)
                                                               at android.view.View.layout(View.java:16772)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2234)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1991)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1147)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6262)

**Comment by MikeAfc** [comment]
猜测是页面退出的时候你做了什么clear的操作，这个时候刚好网络异步回来了
