### ISSUE TITLE
DelegateAdapter.addAdapter时报错

### ISSUE THREAD

**Issue by onionYJK** [alibaba/vlayout#36]
在fragment中将adapter设置给recyclerview之后 调用 DelegateAdapter.addAdapter时报错 java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.

源码中@Override
    public void setHasStableIds(boolean hasStableIds) {
        // do nothing
    }

错误详细见下：

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.dlj.cdbwsoft.esworldpersonal, PID: 28088
                                                                                  java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.
                                                                                      at android.support.v7.widget.RecyclerView$Adapter.setHasStableIds(RecyclerView.java:6424)
                                                                                      at com.alibaba.android.vlayout.DelegateAdapter.addAdapters(DelegateAdapter.java:313)
                                                                                      at com.alibaba.android.vlayout.DelegateAdapter.addAdapters(DelegateAdapter.java:323)
                                                                                      at com.alibaba.android.vlayout.DelegateAdapter.addAdapter(DelegateAdapter.java:331)
                                                                                      at com.dlj.cdbwsoft.esworldpersonal.utils.LoadMoreUtils.bindListener(LoadMoreUtils.java:43)
                                                                                      at com.dlj.cdbwsoft.esworldpersonal.ui.main.home.recommend.HomeRecommendFragment.initData(HomeRecommendFragment.java:102)
                                                                                      at com.dlj.cdbwsoft.esworldpersonal.ui.BaseFragment.onCreateView(BaseFragment.java:52)
                                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                                      at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                                                      at android.view.View.measure(View.java:18596)
                                                                                  	at android.view.ViewGrou

**Comment by longerian** [comment]
看看你的版本，还有release记录，看看是不是解决过的bug

**Comment by onionYJK** [comment]
我是1.0.3版本

**Comment by longerian** [comment]
我对比了一下你的 crash 栈和代码，你用的应该是1.0.2。你更新一下版本。

**Comment by onionYJK** [comment]
compile('com.alibaba.android:vlayout:1.0.3@aar') {
        transitive = true
    }
我是更新了之后还有这个问题才提交的Issue，而且我现在还有这个问题，在fragment中如果recyclerview设置了DelegateAdapter，那么再用DelegateAdapter去addAdapter就会出现这个问题。现在我只能在setAdaoter之前把所有要添加的adapter都添加进去才行，setAdapter之后就不行了。项目我也clean，rebuild好几次。不知道您还需要什么具体一点的信息吗？

**Comment by longerian** [comment]
可能的话demo工程传上来，需要实际代码看一下。

**Comment by onionYJK** [comment]
恩，我把demo发到您的邮箱，您看可以吗？
