### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by g19980115** [alibaba/vlayout#368]
我是嵌套使用的，效果如图，[图片链接](https://user-images.githubusercontent.com/25760230/41896895-6a971a28-7958-11e8-8896-e17f41936c74.jpg)

每个item里面都有一个图片列表`Recyclerview`，这个`Recyclerview`用的是`VirtualLayoutManager` ，
这部分就叫vlayout吧，每个vlayout共用一个`RecycledViewPool`，滑动时极少情况下就会出现这种异常，我这边几天才出现一次，不知道什么情况。

完整异常信息：

```Java
java.lang.IllegalStateException:The specified child already has a parent. You must call removeView() on the child's parent first.
   at android.view.ViewGroup.addViewInner(ViewGroup.java:4941)
   at android.view.ViewGroup.addView(ViewGroup.java:4772)
   at android.view.ViewGroup.addView(ViewGroup.java:4712)
   at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:778)
   at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
   at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8222)
   at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8180)
   at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8168)
   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1573)
   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
   at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)
   at android.view.View.measure(View.java:22170)
   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
   at android.view.View.measure(View.java:22170)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
   at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
   at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
   at android.view.View.measure(View.java:22170)
   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
   at android.view.View.measure(View.java:22170)
   at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8994)
   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1585)
   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
   at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
   at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1077)
   at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4960)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
   at android.view.Choreographer.doCallbacks(Choreographer.java:778)
   at android.view.Choreographer.doFrame(Choreographer.java:710)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
   at android.os.Handler.handleCallback(Handler.java:790)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6753)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by MikeAfc** [comment]
应该是共用RecycledViewPool带来的问题，为什么不把整个feed流做成Recyclerview？

**Comment by g19980115** [comment]
@MikeAfc 这个白色区域，触摸时需要变色，包括下面的评论点赞，用vlayout不知道怎么实现这种嵌套的关系
[图片链接](https://user-images.githubusercontent.com/25760230/42017419-8feaa706-7ae1-11e8-9230-ef1e142803da.jpg)

**Comment by g19980115** [comment]
@MikeAfc 猜测是预加载的问题，嵌套的`vlayout`共用`RecyclerViewPool`，外部`RecyclerView`会预加载，看了下之前的`issue`说`vlayout`不支持预加载，我关闭了外部`RecyclerView`的预加载，上线了一个版本，两天没看到这个异常了
