### ISSUE TITLE
用DelegateAdapter来添加adapter出现的bug

### ISSUE THREAD

**Issue by xuchaoyang168** [alibaba/vlayout#38]
delegateAdapter.addAdapter(new MyTestAdapter(4, new ColumnLayoutHelper()));
   delegateAdapter.addAdapter(new MyTestAdapter(1, new ColumnLayoutHelper()));
  delegateAdapter.addAdapter(0, new MyTestAdapter(2, new ColumnLayoutHelper()));
通过这种形式添加adapter之后，会出现崩溃问题，应该是AdapterDataObserver的mStartPosition和index错乱导致的

**Comment by onionYJK** [comment]
恩，我也是遇到这个问题，我是在fragment中会出现，activity里就没问题，之前我提交过Issues，回复的是版本问题，但是我是1.0.3，是最新版本，还是这个问题。

**Comment by longerian** [comment]
有demo代码先传到github上 我们抽空查一下

**Comment by longerian** [comment]
还有具体的错误日志是什么， 应该贴上来。

**Comment by a4081675** [comment]
请问这问题解决了么?我也出现这问题了     
 java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6322)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                       at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1607)
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:978)
                                                                       at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:108)
                                                                       at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:85)
                                                                       at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:264)
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
                                                                       at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
                                                                       at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
                                                                       at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                                                       at android.view.View.layout(View.java:17637)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
05-08 16:39:28.955 31222-31222/com.yj.yanjintour E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by windwise** [comment]
我也遇到类似的问题[https://github.com/alibaba/vlayout/issues/62](url)

**Comment by longerian** [comment]
@windwise 你的问题和这个不一样
@xuchaoyang168 index错乱的问题，用1.0.5.1版本测一下，应该改好了。
