### ISSUE TITLE
viewpager+fragment的方式，在viewpager的adapter中设置StickyLayoutHelper helper = new StickyLayoutHelper(true);则会报如下错误，设置成 LinearLayoutHelper helper = new LinearLayoutHelper();则没有问题

### ISSUE THREAD

**Issue by finddreams** [alibaba/vlayout#41]
java.lang.IllegalArgumentException: No view found for id 0x7f0b0079 (com.finddreams.viewstudy:id/viewpager) for fragment DetailFragment{bb89686 #0 id=0x7f0b0079 android:switcher:2131427449:0}
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1293)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                              at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                              at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                              at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                              at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                              at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                              at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                              at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                              at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                              at android.view.View.measure(View.java:18811)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                              at android.view.View.measure(View.java:18811)
                                                                              at com.alibaba.android.vlayout.VirtualLayoutManager.measureChildWithDecorationsAndMargin(VirtualLayoutManager.java:1289)
                                                                              at com.alibaba.android.vlayout.VirtualLayoutManager.measureChild(VirtualLayoutManager.java:1145)
                                                                              at com.alibaba.android.vlayout.layout.StickyLayoutHelper.doMeasure(StickyLayoutHelper.java:545)
                                                                              at com.alibaba.android.vlayout.layout.StickyLayoutHelper.layoutViews(StickyLayoutHelper.java:110)
                                                                              at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:264)
                                                                              at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
                                                                              at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
                                                                              at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
                                                                              at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                              at android.view.View.layout(View.java:16653)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                              at android.view.View.layout(View.java:16653)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                              at android.view.View.layout(View.java:16653)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                              at android.view.View.layout(View.java:16653)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                              at android.view.View.layout(View.java:16653)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          	at android.widget.LinearLayout.onLayout(

**Comment by longerian** [comment]
这个好像不是vlayout抛出来的

**Comment by longerian** [comment]
你先检查一下 『No view found for id 0x7f0b0079 』这个问题。
