### ISSUE TITLE
请问在使用VLayout时,最顶部适配器变化会导致崩溃,详见内容

### ISSUE THREAD

**Issue by PrinceIce10** [alibaba/vlayout#425]
尊敬的阿里团队:
       近期在使用VLayout时,出现崩溃异常,有点疑惑,请不吝赐教.
       首先,我在整个商城项目当中几乎80%的页面都用了VLayout,在购物车中,我的VLayout布局为:HeaderAdapter,EmptyAdapter,SingleAdapter,RecommendAdapter. 第一次进来可以正常显示,无论是空布局或是有数据,当时,当下拉刷新2次以上后会出现下面这个异常,准确的说是,当购物车头部数据结算或是清空后,显示空布局,然后这个时候就会崩溃. 我用了一个 ArrayList<DelegateAdapter.Adapter> listAdapters 去装载子适配器,然后下拉刷新时,将 adapters 列表清空,然后在数据成功返回后又重新装载子适配器,然后 baseAdapter.setAdapters(listAdapters); 但是这样控制依然不行. 
       其实,我的目的很简单, 就是用一个 ArrayList 装载子适配器, 然后根据请求服务器返回的数据来显示不同的情形所匹配的界面.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shoppingmall.shoppingmall, PID: 13671
    java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
        at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:480)
        at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:123)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1629)
        at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1043)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:116)
        at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:92)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:639)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1162)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:182)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:722)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15701)
        at android.view.ViewGroup.layout(ViewGroup.java:5048)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2172)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1929)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1099)
    	at android.view.ViewRootImp
    
    --------- beginning of system
I/Process: Sending signal. PID: 13671 SIG: 9

**Comment by lixi0912** [comment]
看你上诉，应当属于不当使用

* 下拉刷新时清空`adapters`, 然后在数据成功返回后又重新装载子适配器 -> 刷新成功后，创建`adapters`填充到`DelegateAdapter`。
* 目前`vlayout`版本如果`mHasConsistItemType=false`，最好重新调用一次`RecyclerView.setAdapter`或者`RecyclerView.setLayoutManager`,否则有可能出现`ViewHolder`的类型转换异常

> 一点建议

* 固定`adapters`模式，动态管理`adapters`中的数据，比如`ListAdapter`持有`AsyncListDiffer`，更新数据时，只要`listAdapter.getDiffer().submit(list)`，完事。
