### ISSUE TITLE
StaggeredGridLayoutHelper NullPointerException

### ISSUE THREAD

**Issue by yuwu** [alibaba/vlayout#45]
版本v1.0.4， 随机出现

java.lang.NullPointerException
                                                                   at com.alibaba.android.vlayout.layout.StaggeredGridLayoutHelper.getMinStart(StaggeredGridLayoutHelper.java:824)
                                                                   at com.alibaba.android.vlayout.layout.StaggeredGridLayoutHelper.computeAlignOffset(StaggeredGridLayoutHelper.java:418)
                                                                   at com.alibaba.android.vlayout.VirtualLayoutManager.computeAlignOffset(VirtualLayoutManager.java:333)
                                                                   at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.updateLayoutStateExpose(ExposeLinearLayoutManagerEx.java:894)
                                                                   at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.scrollInternalBy(ExposeLinearLayoutManagerEx.java:960)
                                                                   at com.alibaba.android.vlayout.VirtualLayoutManager.scrollInternalBy(VirtualLayoutManager.java:463)
                                                                   at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.scrollVerticallyBy(ExposeLinearLayoutManagerEx.java:938)
                                                                   at com.alibaba.android.vlayout.VirtualLayoutManager.scrollVerticallyBy(VirtualLayoutManager.java:67)
                                                                   at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4726)
                                                                   at android.os.Handler.handleCallback(Handler.java:730)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:525)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by longerian** [comment]
在1.0.9里fix了
