### ISSUE TITLE
removeAdapter后出现的问题

### ISSUE THREAD

**Issue by softrice** [alibaba/vlayout#455]
Called removeDetachedView with a view which is not flagged as tmp detached.ViewHolder{8838ca position=11 id=-1, oldPos=-1, pLpos:-1} com.vdian.transaction.widget.TransactionRecycleView{189ea3b VFED.V... ......ID 0,0-1080,1667 #54050032 com.vdian.android.wdb.transaction:id/cart_recycler_view}, adapter:com.alibaba.android.vlayout.DelegateAdapter@1b8e558, layout:com.alibaba.android.vlayout.VirtualLayoutManager@baaa6b1, context:com.vdian.android.wdb.main.ui.activity.MainTabsActivity@f1fb457
    java.lang.IllegalArgumentException: Called removeDetachedView with a view which is not flagged as tmp detached.ViewHolder{8838ca position=11 id=-1, oldPos=-1, pLpos:-1} com.vdian.transaction.widget.TransactionRecycleView{189ea3b VFED.V... ......ID 0,0-1080,1667 #54050032 com.vdian.android.wdb.transaction:id/cart_recycler_view}, adapter:com.alibaba.android.vlayout.DelegateAdapter@1b8e558, layout:com.alibaba.android.vlayout.VirtualLayoutManager@baaa6b1, context:com.vdian.android.wdb.main.ui.activity.MainTabsActivity@f1fb457
        at android.support.v7.widget.RecyclerView.removeDetachedView(RecyclerView.java:3898)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5610)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1628)
        at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1143)
        at com.alibaba.android.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:330)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:741)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1161)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:536)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at in.srain.cube.views.ptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:260)
        at in.srain.cube.views.ptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:229)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
2019-06-12 18:43:42.287 7413-7413/com.koudai.weidian.buyer E/CrashHandler:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2530)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2246)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1426)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6873)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by softrice** [comment]
removeAdapter一个StickyLayoutHelper的adapter后，偶发这个错误。
界面比较复杂,有多种类型adapter,比较难定位。
