### ISSUE TITLE
ViewHolder复用导致滑动卡顿

### ISSUE THREAD

**Issue by a4081675** [alibaba/vlayout#51]
@SuppressWarnings("unchecked")
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        Pair<AdapterDataObserver, Adapter> pair = findAdapterByPosition(position);
        if (pair == null) {
            return;
        }

        pair.second.onBindViewHolder(holder, position - pair.first.mStartPosition);
        pair.second.onBindViewHolderWithOffset(holder, position - pair.first.mStartPosition, position);
    }
这个地方比如我添加了4个adapter.第一屏显示了3个adapter,等滑到第四个adapter的时候,holder返回的是第一个adapter,然后就报错了.页面在报错的那个地方卡顿一下滑动停止.

**Comment by longerian** [comment]
你看一下错误日志是什么

**Comment by a4081675** [comment]
错误日志   是类型转换异常
我用的是databind, holder里面存放的ViewDataBinding,    滑动到第四个adapter的时候返回的是第一个adapter的holder.然后把值传进去的时候就类型转换异常了.
@Override
    public void onBindViewHolder(BaseBindingVH<B> holder, int position) {
        holder.getBinding().setVariable(BR.data,mDatas.get(position));
        holder.getBinding().setVariable(BR.itemP, ItemPresenter);
        holder.getBinding().executePendingBindings();
    }

**Comment by nk-null** [comment]
我也出现了，应该是添加多个Adapter，每个Adapter里面又有不同的的ViewHolder，导致ViewHolder复用的时候类型转换异常。

具体log
W/VirtualLayoutManager: java.lang.ClassCastException: com.gznt.mdmphone.view.adapter.MainLinearAdapter$MainLinearViewHolder cannot be cast to com.gznt.mdmphone.view.adapter.MainGridAdapter$MainGridViewHolder
                                                                             at com.gznt.mdmphone.view.adapter.MainGridAdapter.onBindViewHolder(MainGridAdapter.java:26)
                                                                             at com.gznt.emm.common.customview.vlayout.DelegateAdapter.onBindViewHolder(DelegateAdapter.java:138)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                             at com.gznt.emm.common.customview.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1607)
                                                                             at com.gznt.emm.common.customview.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:979)
                                                                             at com.gznt.emm.common.customview.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:315)
                                                                             at com.gznt.emm.common.customview.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:264)
                                                                             at com.gznt.emm.common.customview.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:575)
                                                                             at com.gznt.emm.common.customview.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
                                                                             at com.gznt.emm.common.customview.vlayout.ExposeLinearLayoutManagerEx.scrollInternalBy(ExposeLinearLayoutManagerEx.java:965)
                                                                             at com.gznt.emm.common.customview.vlayout.VirtualLayoutManager.scrollInternalBy(VirtualLayoutManager.java:464)
                                                                             at com.gznt.emm.common.customview.vlayout.ExposeLinearLayoutManagerEx.scrollVerticallyBy(ExposeLinearLayoutManagerEx.java:938)
                                                                             at com.gznt.emm.common.customview.vlayout.VirtualLayoutManager.scrollVerticallyBy(VirtualLayoutManager.java:68)
                                                                             at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1680)
                                                                             at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2837)
                                                                             at android.view.View.dispatchTouchEvent(View.java:8504)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2387)
                                                                             at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1734)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2830)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                         	at com.android.internal.policy.impl

**Comment by nk-null** [comment]
DelegateAdapter delegateAdapter = new DelegateAdapter(vManager, false);
创建delegateAdapter设置第二个参数为false，即不共享不同子Adapter的ViewHolder，即可避免类型转换异常

**Comment by a4081675** [comment]
谢了   还真是    没注意这参数

**Comment by longerian** [comment]
@nk-null  @a4081675 确实，这个参数需要重视，没特别说明，我会在readme里注明一下。

这个参数先详细介绍可以参考:http://pingguohe.net/2017/05/03/the-beauty-of-math-in-vlayout.html
