### ISSUE TITLE
OPPO 5.0 手机资源文件找不到

### ISSUE THREAD

**Issue by lu769257351** [alibaba/vlayout#521]
02-08 15:13:36.965   391   391 E AndroidRuntime: android.view.InflateException: Binary XML file line #42: Error inflating class <unknown>
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.addcn.oldcarmodule.detail.adapter.BannerSubAdapter.onCreateViewHolder(BannerSubAdapter.java:71)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.addcn.oldcarmodule.detail.adapter.BannerSubAdapter.onCreateViewHolder(BannerSubAdapter.java:25)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:128)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.b$c.a(ExposeLinearLayoutManagerEx.java:1629)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.VirtualLayoutManager$c.a(VirtualLayoutManager.java:1043)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.a.a.a(BaseLayoutHelper.java:116)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.a.g.b(LinearLayoutHelper.java:88)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.a.a.a(BaseLayoutHelper.java:318)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.VirtualLayoutManager.a(VirtualLayoutManager.java:639)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.b.a(ExposeLinearLayoutManagerEx.java:1162)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.b.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:463)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.View.layout(View.java:16024)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5229)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
02-08 15:13:36.965   391   391 E AndroidRuntime: 	at android.view.View.layout(View

**Comment by lu769257351** [comment]
在继承AppCompatActivity的activity中使用DelegateAdapter时，在adapter的xml中有包含TextView会在OPPO5.0系统中出现上面的错误
