### ISSUE TITLE
减少某继承extends DelegateAdapter.Adapter的Adpater里数据后崩溃

### ISSUE THREAD

**Issue by mabeijianxi** [alibaba/vlayout#69]
里面有两个adapter，分别是包含GridLayoutHelper与SingleLayoutHelper，当我动态减少包含GridLayoutHelper的adaprer里面一些数据后重新 调用了GridLayoutHelper的setItemCount,这时候调用其notifyDataSetChanged发生如下奔溃

In thread: Thread[main,5,main]
                                                                                 UncaughtException detected: java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
                                                                                     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5289)
                                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4551)
                                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
                                                                                     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1607)
                                                                                     at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:978)
                                                                                     at com.alibaba.android.vlayout.layout.GridLayoutHelper.layoutViews(GridLayoutHelper.java:322)
                                                                                     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:264)
                                                                                     at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
                                                                                     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
                                                                                     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
                                                                                     at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
                                                                                     at

**Comment by mabeijianxi** [comment]
再次调用delegateAdapter.setAdapters(adapters)倒是不会奔溃，但是我看这个方法把所有数据又初始化了一遍，会不会不太好啊

**Comment by longerian** [comment]
像是内部索引错乱引起的。重新调用setAdapter会重建索引。

**Comment by mabeijianxi** [comment]
请问是否还有更好的办法可以重建索引，如果没有那对于有大量交互的item是不是不太试用重复setAdapter，比如会频繁的删除与增加条目

**Comment by longerian** [comment]
索引是需要重建的，在调用子Adapter的notifyDataSetChanged应该会重建；要看你的Adapter怎么写，检查一下减少数据之后，adapter返回的itemCount和layoutHelper返回的itemCount一致。

**Comment by clgg** [comment]
这块好像有点问题，直接调用delegateAdapter.addAdapter()没问题，但是调用delegateAdapter.addAdapter(position,adapter) 就会出问题，用setAdapters 也是可以的，不知道为啥会这个样子

**Comment by longerian** [comment]
@clgg  delegateAdapter.addAdapter(position,adapter)  这一处有个bug，已经解决，周末发个版本。

**Comment by longerian** [comment]
1.0.7
