### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=61; index=-1

### ISSUE THREAD

**Issue by iielse** [alibaba/vlayout#81]
05-25 11:29:21.475 20093-20093/com.* W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=61; index=-1
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:828)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.text.StaticLayout.out(StaticLayout.java:747)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.text.StaticLayout.generate(StaticLayout.java:451)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.text.StaticLayout.<init>(StaticLayout.java:145)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.TextView.makeSingleLayout(TextView.java:6294)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.TextView.makeNewLayout(TextView.java:6140)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.TextView.onMeasure(TextView.java:6516)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.view.View.measure(View.java:16555)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1073)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:611)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.view.View.measure(View.java:16555)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.view.View.measure(View.java:16555)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1257)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:611)
05-25 11:29:21.485 20093-20093/com.* W/System.err:     at android.view.View.measure(View.java:16555)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.view.View.measure(View.java:16555)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.view.View.measure(View.java:16555)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.measureChildWithDecorationsAndMargin(VirtualLayoutManager.java:1308)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.measureChildWithMargins(VirtualLayoutManager.java:1157)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.layout.SingleLayoutHelper.layoutViews(SingleLayoutHelper.java:110)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:273)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
05-25 11:29:21.490 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-25 11:29:21.495 20093-20093/com.* W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.View.layout(View.java:14873)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4651)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2051)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1805)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1038)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5893)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:593)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:562)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.os.Looper.loop(Looper.java:136)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5315)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
05-25 11:29:21.500 20093-20093/com.* W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by iielse** [comment]
```
dependencies {
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:recyclerview-v7:24.2.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile ('com.alibaba.android:vlayout:1.0.6@aar') {
        transitive = true
    }
}
```

**Comment by iielse** [comment]
不好意思，对不起，是我自己代码复制的原因写错了。尴尬
